version: '3'

services:
  app:
    build: .
    depends_on: 
      - redis
    volumes: 
      - .:/home/app
  redis:
    image: "redis:alpine"
    ports: 
      - 6379:6379
    volumes:
      - ../data/redis:/data